# render.yaml - Place this in your project root
services:
  # Backend API Service
  - type: web
    name: financial-friend-api
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend Static Site
  - type: web
    name: financial-friend-frontend
    runtime: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html